### ISSUE TITLE
SVG doesn't display on iOS, both Safari and Chrome

### ISSUE THREAD

**Issue by domsson** [domsson/freedom-clock#1]
Yeah. iPhone users on Safari and Chrome see this:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7917999/226777538-183762af-2532-4f6b-896d-113c791e93ba.png)

In other words, the SVGs are not displaying at all.

**Comment by ellieayla** [comment]
Same on Safari Version 15.4 (17613.1.17.1.13) on MacOS 12.3.1 (21E258).

Tapping the "_What the fuck?_" link doesn't show any information about why the height on the `time` element is 100% of 0px.

**Comment by domsson** [comment]
> the height on the `time` element is 100% of 0px.

Thank you, @ellieayla - I think you were spot on! I gave `time` an explicit height and now it seems to work. At least I was able to confirm it on the iPhone of one friend. If you can also confirm it working on MacOS, then I'll close this as fixed.

**Comment by domsson** [comment]
I managed to get someone to try it on a MacBook with both Safari and Chrome and they confirmed it works now.
